name: 'Unofficial ReSharper Annotations'
description: 'Annotates code with ReSharper inspections'
inputs:
  solution:
    description: 'Filepath of the solution to inspect'
    required: true
  dotnet-version:
    required: true
    description: '.NET SDK version'
    default: '6.0.x'
  resharper-version:
    description: 'JetBrains.ReSharper.GlobalTools version'
    required: true
    default: '2023.1.3'
  treat-warnings-as-errors:
    description: 'Whether to treat any warnings as errors'
    required: false
    default: 'false'
  extra-args:
    description: 'Extra arguments to pass to inspectcode'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Install ReSharper CLI
      shell: bash
      run: |
        dotnet new tool-manifest
        dotnet tool install JetBrains.ReSharper.GlobalTools --version ${{ inputs.resharper-version }}
        dotnet tool restore

    - name: Inspect code with ReSharper
      shell: bash
      run: >
        dotnet jb inspectcode ${{ inputs.solution }}
        ${{ inputs.extra-args }}
        --output=report
        --swea
        --severity=WARNING
        --properties:Configuration=Release

    - name: Annotate with inspections
      uses: VMelnalksnis/resharper-inspect-action/resharper-annotate@v0.3.0
      with:
        report: report
        treat-warnings-as-errors: ${{ inputs.treat-warnings-as-errors }}
