name: 'Unofficial ReSharper Annotations'
description: 'Annotates code with ReSharper inspections'
inputs:
  report:
    description: 'Filepath of the ReSharper inspection report'
    required: true
  treat-warnings-as-errors:
    description: 'Whether to treat any warnings as errors'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/vmelnalksnis/resharper-annotate:v0.3.0'
  args:
    - ${{ inputs.report }}
    - ${{ inputs.treat-warnings-as-errors }}
