name: publish

on:
  push:
    branches:
      - master

jobs:
  publish-resharper-annotate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the resharper-annotate Docker image
        run: |
          docker build ./resharper-annotate --tag ghcr.io/vmelnalksnis/resharper-annotate:v0.2.5
          docker push ghcr.io/vmelnalksnis/resharper-annotate:latest
