name: test

on:
  pull_request:
    branches:
      - master

jobs:
  test-action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 6.0.x

      - name: Restore dependencies
        working-directory: sample/
        run: dotnet restore

      - name: Build
        working-directory: sample/
        run: dotnet build --configuration Release --no-restore /nologo /clp:NoSummary

      - name: Annotate
        uses: ./
        with:
          solution: sample/HelloWorld.sln
